version: '3.9'

services:
  db:
    build: .docker/mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      default:
        aliases:
          - 'db.${APP_NAME}.local'

  apache:
    build: .docker/apache
    ports:
      - "8004:80"
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - ${API_APP}:/var/www/api
    depends_on:
      - api
    networks:
      default:
        aliases:
          - 'api.${APP_NAME}.local'
          - 'api'

  api:
    build: .docker/php
    volumes:
      - ${API_APP}:/var/www/api
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}?serverVersion=mariadb-10.4.8
    depends_on:
      - db

  # elasticsearch server (official image)
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  # https://hub.docker.com/_/elasticsearch/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - "xpack.security.enabled=false"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"

  # kibana (official image)
  # https://hub.docker.com/_/kibana
  kibana:
    container_name: sb-kibana
    image: docker.elastic.co/kibana/kibana:6.8.6
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://sb-elasticsearch"
    depends_on:
      - elasticsearch

  nest:
    build: .docker/nest
    ports:
      - 8000:3000
    volumes:
      - ${NEST_APP}:/home/node/app
    depends_on:
      - db
    networks:
      default:
        aliases:
          - 'nest.${APP_NAME}.local'

  nginx:
    build: .docker/nginx
    volumes:
      - ${FRONT_APP}/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases:
          - 'app.${APP_NAME}.local'

  front:
    build: .docker/angular
    ports:
      - "4200:4200"
    volumes:
      - ${FRONT_APP}:/home/node/app
    tty: true
    expose:
      - "4200"