version: '3.9'

services:
  db:
    build: .docker/mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      default:
        aliases:
          - 'db.${APP_NAME}.local'

  apache:
    build: .docker/apache
    ports:
      - "8004:80"
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - ${API_APP}:/var/www/api
    depends_on:
      - php
    networks:
      default:
        aliases:
          - 'api.${APP_NAME}.local'
          - 'api'

  api:
    build: .docker/php
    volumes:
      - ${API_APP}:/var/www/api
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=mariadb-10.4.8
    depends_on:
      - db

  nest:
    build: .docker/nest
    ports:
      - 8000:3000
    volumes:
      - ${NEST_APP}:/home/node/app
    depends_on:
      - db
    networks:
      default:
        aliases:
          - 'nest.${APP_NAME}.local'

  nginx:
    build: .docker/nginx
    volumes:
      - ${FRONT_APP}/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases:
          - 'app.${APP_NAME}.local'

  front:
    build: .docker/angular
    ports:
      - "4200:4200"
    volumes:
      - ${FRONT_APP}:/home/node/app
    tty: true
    expose:
      - "4200"